#!/bin/sh




Help()
{
   echo ",table - generate Markdown tables"
   echo
   echo "Syntax: ,table [-h] column-count"
   echo "options:"
   echo "h     Print this Help."
   echo
   echo "arguments:"
   echo "column-count   How many columns you want in your table"
   echo
}

while getopts ":h" option; do
   case $option in
      h) # display Help
         Help
         exit;;
   esac
done

if [ -z "$1" ]
then
    echo "Usage: ,table [column-count]";
    exit 1;
else
    # Print header line with _ as placeholder
    for i in $(seq 1 $1);
    do
        printf '%s_' "|"
    done
    echo "|";

    # Print the header separator
    for i in $(seq 1 $1);
    do
        printf '%s-' "|"
    done
    echo "|"

    # Print first row with _ as placeholder
    for i in $(seq 1 $1);
    do
        printf '%s_' "|"
    done
    echo "|";
fi

exit 0;
